# Generated by Django 4.0.5 on 2022-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=1000)),
                ('partOf', models.CharField(blank=True, max_length=1000, null=True)),
                ('detection_type', models.IntegerField(choices=[(1, 'Image'), (2, 'HTML'), (3, 'Text')])),
                ('hasChanged', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
