# Generated by Django 4.0.5 on 2022-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='hasChanged',
        ),
        migrations.AddField(
            model_name='tasks',
            name='threshold',
            field=models.FloatField(default=1.0),
        ),
    ]
