# Generated by Django 4.0.5 on 2022-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_mainapp', '0002_remove_tasks_haschanged_tasks_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='partOf',
            field=models.CharField(default='full', max_length=1000),
        ),
    ]
