# Generated by Django 4.0.5 on 2022-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_mainapp', '0002_remove_tasks_haschanged_tasks_threshold_tasks_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tasks',
            constraint=models.UniqueConstraint(fields=('user', 'web_url'), name='wcd_mainapp_tasks_unique'),
        ),
    ]
