# Generated by Django 4.0.5 on 2022-07-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wcd_mainapp', '0003_alter_tasks_partof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='detection_type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'HTML'), (3, 'Text')], default=3),
        ),
    ]
