# Generated by Django 4.0.5 on 2022-07-25 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcd_mainapp', '0003_tasks_wcd_mainapp_tasks_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='threshold',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
