# Generated by Django 4.0.5 on 2022-07-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_confirmation_mail_sent',
        ),
    ]
